```{r}
# Set the working directory
setwd("D:/UNI_COURSES/COMP 1810 Data and Web Analytics/R/Draft")

# Read the CSV file with specified encoding
data <- read.csv("missingLemonade2016.csv", fileEncoding = "ISO-8859-1")

data_dimensions <- dim(data)
num_rows <- nrow(data)
num_columns <- ncol(data)

# Print the dimensions
cat("The data frame has", num_rows, "rows and", num_columns, "columns.\n")

# Optional: Display a summary of the data frame
summary(data)

```

```{r}
sapply(data, class)


```


```{r}
na_counts <- colSums(is.na(data))

# Print the number of NA values for each column
print(na_counts)
```

```{r}
df$Location = ifelse(df$Location == "na" | is.na(df$Location), "Unknown", df$Location)
View(df)
```

```{r}
df$Location[is.na(df$Location) | df$Location == "na"] = "unknown"
View(df)
```

```{r}
df$Lemon[is.na(df$Lemon)] <- round(mean(df$Lemon, na.rm = TRUE))
```

```{r}
df$Orange <- as.numeric(df$Orange)  # Convert "Orange" column to numeric
df$Orange[is.na(df$Orange) | df$Orange == "na" | df$Orange == ""] = 0
df$Orange[df$Orange == 0] = round(median(df$Orange, na.rm = TRUE))
View(df)
```

```{r}
df$Price[df$Price == "--" | is.na(df$Price)] = df$Price[i-1]

indexes = which(is.na(df$Price))
print(indexes)
df$Price[indexes] = df$Price[indexes-1]
View(df)
```


```{r}
# Check the data types of df$Total.Sales and df$Price
class(df$Total.Sales)
class(df$Price)

# Convert df$Total.Sales and df$Price to numeric if they are not already
df$Total.Sales <- as.numeric(df$Total.Sales)
df$Price <- as.numeric(df$Price)

# Check if there are any NA or non-numeric values in df$Total.Sales and df$Price after conversion
sum(is.na(df$Total.Sales))
sum(is.na(df$Price))

# If there are non-numeric values, handle them appropriately (e.g., remove them or impute them)

# Calculate Revenue
df$Revenue <- paste("$", df$Total.Sales * df$Price)
rev = class(df$Revenue)
print(rev)
# View the dataframe
View(df)


```



